spring:
  application:
    name: service-student
  datasource:
    url: jdbc:mysql://localhost:3308/micro-student-db
    username: root
    password: sistemas
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  cloud:
    openfeign:
      discovery:
        enabled: true

server:
  port: 3063

token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351